// app/control/page.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

function btnClass(primary = false) {
return [
"px-4 py-3 rounded-xl border text-sm",
"bg-neutral-900 border-neutral-700 text-white",
primary ? "ring-1 ring-emerald-500/40 border-emerald-600/40" : "",
].join(" ");
}

export default function ControlPage() {
const sp = useSearchParams();
const sidFromUrl = sp.get("sid") || "";
const [sid, setSid] = useState(sidFromUrl);

useEffect(() => {
if (sidFromUrl) setSid(sidFromUrl);
}, [sidFromUrl]);

const ready = useMemo(() => sid.trim().length > 0, [sid]);

async function send(type: "start" | "stop" | "reset" | "tag") {
if (!ready) return;

await fetch("/api/remote", {
method: "POST",
headers: { "Content-Type": "application/json" },
body: JSON.stringify({
sid,
type,
payload: { source: "controller" },
}),
});
}

return (
<div className="min-h-screen bg-black text-white">
<div className="max-w-xl mx-auto p-6">
<div className="flex items-center gap-2 mb-5">
<div className="h-2 w-2 rounded-full bg-emerald-400" />
<div className="text-lg font-semibold">Axis Control</div>
</div>

<div className="rounded-2xl border border-neutral-800 bg-neutral-950 p-4 mb-4">
<div className="text-xs text-neutral-400 mb-2">Target Session (sid)</div>
<input
value={sid}
onChange={(e) => setSid(e.target.value)}
placeholder="Paste sid from /run?sid=..."
className="w-full bg-black border border-neutral-800 rounded-xl px-3 py-3 text-sm outline-none"
/>
<div className="text-xs text-neutral-500 mt-2">
Tip: open Control using the runner link: <span className="text-neutral-300">/control?sid=XXXX</span>
</div>
</div>

<div className="grid grid-cols-2 gap-3">
<button className={btnClass(true)} onClick={() => send("start")} disabled={!ready}>
Start
</button>
<button className={btnClass()} onClick={() => send("stop")} disabled={!ready}>
Stop
</button>
<button className={btnClass()} onClick={() => send("reset")} disabled={!ready}>
Reset
</button>
<button className={btnClass(true)} onClick={() => send("tag")} disabled={!ready}>
Tag Decision
</button>
</div>

{!ready && (
<div className="text-sm text-amber-300/90 mt-4">
Not paired yet. Paste the runner <b>sid</b> or open the Control link generated by Run.
</div>
)}
</div>
</div>
);
}